/**
 * A curated universe of large-, liquid, well-known US listings.
 *
 * Alpaca retired API-key access to its screener and symbol-metadata endpoints
 * (they are OAuth-only now), so Market Pulse uses this list as the fallback
 * universe for top movers (priced via the v2 snapshots endpoint) and as a
 * last-resort autocomplete source. A few hundred thousand micro-caps won't
 * appear here — that's an honest trade-off for a free-plan app, and better
 * than a dead card on the page.
 */

export interface PopularSymbol {
  symbol: string;
  name: string;
}

export const POPULAR_SYMBOLS: PopularSymbol[] = [
  { symbol: "AAPL", name: "Apple Inc." },
  { symbol: "MSFT", name: "Microsoft Corporation" },
  { symbol: "NVDA", name: "NVIDIA Corporation" },
  { symbol: "AMZN", name: "Amazon.com, Inc." },
  { symbol: "META", name: "Meta Platforms, Inc." },
  { symbol: "TSLA", name: "Tesla, Inc." },
  { symbol: "GOOGL", name: "Alphabet Inc. (Class A)" },
  { symbol: "GOOG", name: "Alphabet Inc. (Class C)" },
  { symbol: "AVGO", name: "Broadcom Inc." },
  { symbol: "BRK.B", name: "Berkshire Hathaway Inc. (Class B)" },
  { symbol: "LLY", name: "Eli Lilly and Company" },
  { symbol: "JPM", name: "JPMorgan Chase & Co." },
  { symbol: "V", name: "Visa Inc." },
  { symbol: "MA", name: "Mastercard Inc." },
  { symbol: "UNH", name: "UnitedHealth Group Incorporated" },
  { symbol: "XOM", name: "Exxon Mobil Corporation" },
  { symbol: "WMT", name: "Walmart Inc." },
  { symbol: "COST", name: "Costco Wholesale Corporation" },
  { symbol: "PG", name: "Procter & Gamble Co." },
  { symbol: "JNJ", name: "Johnson & Johnson" },
  { symbol: "HD", name: "Home Depot, Inc." },
  { symbol: "MRK", name: "Merck & Co., Inc." },
  { symbol: "BAC", name: "Bank of America Corp." },
  { symbol: "ABBV", name: "AbbVie Inc." },
  { symbol: "KO", name: "Coca-Cola Company" },
  { symbol: "PEP", name: "PepsiCo, Inc." },
  { symbol: "CRM", name: "Salesforce, Inc." },
  { symbol: "ADBE", name: "Adobe Inc." },
  { symbol: "NFLX", name: "Netflix, Inc." },
  { symbol: "INTC", name: "Intel Corporation" },
  { symbol: "AMD", name: "Advanced Micro Devices, Inc." },
  { symbol: "QCOM", name: "QUALCOMM Incorporated" },
  { symbol: "CSCO", name: "Cisco Systems, Inc." },
  { symbol: "ORCL", name: "Oracle Corporation" },
  { symbol: "IBM", name: "International Business Machines Corp." },
  { symbol: "DIS", name: "Walt Disney Co." },
  { symbol: "CMCSA", name: "Comcast Corporation" },
  { symbol: "VZ", name: "Verizon Communications Inc." },
  { symbol: "T", name: "AT&T Inc." },
  { symbol: "TMUS", name: "T-Mobile US, Inc." },
  { symbol: "PYPL", name: "PayPal Holdings, Inc." },
  { symbol: "NKE", name: "Nike, Inc." },
  { symbol: "MCD", name: "McDonald's Corporation" },
  { symbol: "CMG", name: "Chipotle Mexican Grill, Inc." },
  { symbol: "SBUX", name: "Starbucks Corporation" },
  { symbol: "YUM", name: "Yum! Brands, Inc." },
  { symbol: "CAT", name: "Caterpillar Inc." },
  { symbol: "BA", name: "Boeing Co." },
  { symbol: "GE", name: "GE Aerospace" },
  { symbol: "HON", name: "Honeywell International Inc." },
  { symbol: "UPS", name: "United Parcel Service, Inc." },
  { symbol: "FDX", name: "FedEx Corporation" },
  { symbol: "DE", name: "Deere & Company" },
  { symbol: "PCAR", name: "PACCAR Inc." },
  { symbol: "F", name: "Ford Motor Company" },
  { symbol: "GM", name: "General Motors Company" },
  { symbol: "RIVN", name: "Rivian Automotive, Inc." },
  { symbol: "PLTR", name: "Palantir Technologies Inc." },
  { symbol: "COIN", name: "Coinbase Global, Inc." },
  { symbol: "HOOD", name: "Robinhood Markets, Inc." },
  { symbol: "SOFI", name: "SoFi Technologies, Inc." },
  { symbol: "AFRM", name: "Affirm Holdings, Inc." },
  { symbol: "UPST", name: "Upstart Holdings, Inc." },
  { symbol: "SHOP", name: "Shopify Inc." },
  { symbol: "SNAP", name: "Snap Inc." },
  { symbol: "UBER", name: "Uber Technologies, Inc." },
  { symbol: "LYFT", name: "Lyft, Inc." },
  { symbol: "ABNB", name: "Airbnb, Inc." },
  { symbol: "DASH", name: "DoorDash, Inc." },
  { symbol: "AC", name: "Air Canada" },
  { symbol: "SPY", name: "SPDR S&P 500 ETF Trust" },
  { symbol: "QQQ", name: "Invesco QQQ Trust" },
  { symbol: "IWM", name: "iShares Russell 2000 ETF" },
  { symbol: "DIA", name: "SPDR S&P Dow Jones Industrial ETF" },
  { symbol: "VTI", name: "Vanguard Total Stock Market ETF" },
  { symbol: "VOO", name: "Vanguard S&P 500 ETF" },
  { symbol: "SCHW", name: "Charles Schwab Corporation" },
  { symbol: "GS", name: "Goldman Sachs Group, Inc." },
  { symbol: "MS", name: "Morgan Stanley" },
  { symbol: "WFC", name: "Wells Fargo & Company" },
  { symbol: "C", name: "Citigroup Inc." },
  { symbol: "TS", name: "TotalEnergies SE" },
  { symbol: "CVX", name: "Chevron Corporation" },
  { symbol: "COP", name: "ConocoPhillips" },
  { symbol: "SLB", name: "Schlumberger Limited" },
  { symbol: "OXY", name: "Occidental Petroleum Corp." },
  { symbol: "TMO", name: "Thermo Fisher Scientific Inc." },
  { symbol: "ABT", name: "Abbott Laboratories" },
  { symbol: "DHR", name: "Danaher Corporation" },
  { symbol: "PFE", name: "Pfizer Inc." },
  { symbol: "TGT", name: "Target Corporation" },
  { symbol: "LOW", name: "Lowe's Companies, Inc." },
  { symbol: "TJX", name: "TJX Companies, Inc." },
  { symbol: "BKNG", name: "Booking Holdings Inc." },
  { symbol: "MAR", name: "Marriott International, Inc." },
  { symbol: "GEHC", name: "GE HealthCare" },
  { symbol: "PANW", name: "Palo Alto Networks, Inc." },
  { symbol: "CRWD", name: "CrowdStrike Holdings, Inc." },
  { symbol: "NET", name: "Cloudflare, Inc." },
  { symbol: "DDOG", name: "Datadog, Inc." },
  { symbol: "NOW", name: "ServiceNow, Inc." },
  { symbol: "UBS", name: "UBS Group AG" },
];
